### ISSUE TITLE
[v1.20-rc.1] Set3DProjection error

### ISSUE THREAD

**Issue by BradyThe** [fuami/Spyglass#6]
Great mod, unfortunately v1.20 introduced some changes that stopped the functionality of spyglass.

**Game version:** v1.20-rc.1
**Mod version:** 0.5.1

```
[Error] While preforming spyglass.src.Client.Patches.Set3DProjection : System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at spyglass.src.Client.Patches.Set3DProjection.patch(Harmony harmony) in C:\Users\Fuami\source\repos\spyglass\spyglass\src\Client\Patches\Set3DProjection.cs:line 42
   at spyglass.src.ClientPatcher.Start(ILogger logger) in C:\Users\Fuami\source\repos\spyglass\spyglass\src\Client\ClientPatcher.cs:line 39
```

**Comment by fuami** [comment]
Thanks for the report, I've pushed a new version that should resolve the patching issue.
